Update test-Auto-Package.yml

diff --git a/.github/workflows/test-Auto-Package.yml b/.github/workflows/test-Auto-Package.yml
--- a/.github/workflows/test-Auto-Package.yml
+++ b/.github/workflows/test-Auto-Package.yml
@@ -168,7 +168,7 @@ jobs:
         mv -f feeds/packages/lang feeds/packages/lang.b
         mv -f feeds/packages feeds/packages.b
         mkdir package/feeds/custom
-        mv -f custom.b/{wxbase,lib*,rapidjson,jpcre2,quickjspp,qtbase,qttools,rblibtorrent} package/feeds/custom/
+        cp -rf custom.b/{wxbase,lib*,rapidjson,jpcre2,toml11,gn,curl,quickjspp,qt*,libtorrent*,openssl,mbedtls,ppp,cups,nftables} package/feeds/custom/ || true
 
     - name: Compile the firmware
       run: |
@@ -180,13 +180,15 @@ jobs:
              cp -rf custom.b/$ipk package/feeds/custom/
              if [[ $ipk != luci-* ]]; then
               mv -f feeds/packages.b feeds/packages
-              [ "$(grep -E "(PKG_BUILD_DEPENDS|packages/lang|meson.mk)" package/feeds/custom/$ipk/Makefile)" ] && mv feeds/packages/lang.b feeds/packages/lang
+              mv feeds/packages/lang.b feeds/packages/lang
+              [ "$(grep "PKG_BUILD_DEPENDS" package/feeds/custom/$ipk/Makefile)" ] || mv feeds/packages/lang/node feeds/packages/lang/node.b
              fi
-             make package/$ipk/compile -j$(($(nproc)+1)) || make package/$ipk/compile V=s >>error_$ipk.log 2>&1 || true
+             (make package/$ipk/compile -j$(($(nproc)+1)) || make package/$ipk/compile V=s 2>&1 | tee error_$ipk.log | grep -i "Error 2" || rm -rf error_$ipk.log) || true
              if [[ $ipk != luci-* ]]; then
-              mv feeds/packages/lang feeds/packages/lang.b || true
+              mv -f feeds/packages/lang feeds/packages/lang.b 2>/dev/null || true
+              mv -f feeds/packages/lang.b/node.b feeds/packages/lang.b/node 2>/dev/null || true
               mv -f feeds/packages feeds/packages.b
-              rm -f package/feeds/custom/$ipk
+              rm -rf package/feeds/custom/$ipk
              fi
             }
           for ipk in $(ls custom.b | grep -E "$fpkg"); do
@@ -194,21 +196,25 @@ jobs:
             if [[ "$fpkg" && ! "$during" ]]; then
               comp
             else
-              gitdate=$(curl -H "Authorization: token ${{ secrets.REPO_TOKEN }}" -s "https://api.github.com/repos/love-dy/small-package/commits?path=$ipk&per_page=1" | jq -r '.[0].commit.committer.date')
-              if [ $gitdate != null ]; then
-                gitdate=$(date -d "$gitdate" +%s)
-                now=$(date -d "$(date '+%Y-%m-%d %H:%M:%S')" +%s)
+              gitdate="$(curl -H "Authorization: token ${{ env.REPO_TOKEN }}" -s "https://api.github.com/repos/kiddin9/openwrt-packages/commits?path=$ipk&per_page=1" | jq -r '.[0].commit.committer.date')" || true
+              if [[ "$gitdate" && "$gitdate" != null ]]; then
+                gitdate="$(date -d "$gitdate" +%s)"
+                now="$(date -d "$(date)" +%s)"
                 [ "$during" ] || during="1.05"
                 durings=`echo "$during*60*60*24" | bc`
-                if [[ $(($gitdate + ${durings%.*})) -gt $now ]]; then
-                echo "$gitdate"
-                echo "${durings%.*}"
-                echo "$now"
-                  comp
+                if [[ $(($gitdate + ${durings%.*})) -gt $now && $ipk != luci-base && $ipk != luci-mod-* ]]; then
+                  echo "$((($now - $gitdate)/60/60))" || true
+                  echo "$ipk" >> ipk.txt
                 fi
               fi
             fi
           done
+          if [ -f ipk.txt ]; then
+              for ipk in $(cat ipk.txt)
+              do
+                comp
+              done
+          fi
         echo "status=success" >> $GITHUB_ENV
 
     - name: Check space usage
